spring.application.name: user-service

server:
  port: 9020
  servlet.context-path: /users

jwt.secretKey: asdfladf98a7df89aysf8d9yasiudfha9s87dfa89syudhfa98sdfyaisuhdfa98sfy

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userDB
    username: postgres
    password: mdfa
  jpa.hibernate.ddl-auto: create-drop

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# eureka config
eureka.client.service-url.defaultZone: http://localhost:8761/eureka

kafka.topic:
  user-created-topic: user-created-topic
