spring.application.name: posts-service

server:
  port: 9010
  servlet.context-path: /posts

spring:
  datasource:
    url: jdbc:postgresql://${DB_SERVICE:posts-db}:5432/${DB_NAME:postsDB}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}

  jpa.hibernate.ddl-auto: update

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# eureka config
eureka.client.service-url.defaultZone: http://discovery-server:8761/eureka

kafka:
  topic:
    post-created-topic: post-created-topic
    post-liked-topic: post-liked-topic


